sudo: true
language: haskell

git:
  depth: 5

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  # Cabal
  - ghc: 8.2.2
  - ghc: 8.4.4
  - ghc: 8.6.5
  - ghc: 8.8.3
  - ghc: 8.10.1
  # Stack
  - ghc: 8.8.1
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

install:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

  - |
    if [ -z "$STACK_YAML" ]; then
      ghc --version
      cabal --version
      cabal update
      cabal build --enable-tests
    else
      # install stack
      curl -sSL https://get.haskellstack.org/ | sh

      # build project with stack
      stack --version
      stack build --system-ghc --test --no-run-tests
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal test --enable-tests
    else
      stack test --no-terminal --system-ghc
    fi

notifications:
  email: false
