sudo: true
language: generic

git:
  depth: 5

cache:
  directories:
  - "$HOME/.stack"

matrix:
  include:
  - os: linux
    env: GHC="8.8.3"
  - os: osx
    env: GHC="8.8.3"

install:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version
  - stack build --test --no-run-tests --bench --no-run-benchmarks

script:
  - stack test --no-terminal

notifications:
  email: false
